image: python:3.7

stages:
  - test
  - deploy

pytest:
  coverage: '/TOTAL[\s|\d]+(\d+.\d+%)/'
  script:
    - apt update && apt install -y python3-pip
    - python3 -m pip install pip pytest pytest-cov
    - python3 -m pytest --cov=tests --cov-report html
  artifacts:
    paths:
    - htmlcov/*
  only:
    - master

pages:
  image: alpine:latest
  stage: deploy
  dependencies:
    - pytest
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
  only:
    - master